[project]
name = "casev2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "build123d",
    "ocp-vscode>=2.8.5",
]

[tool.uv.sources]
build123d = { git = "https://github.com/gumyr/build123d.git" }
