[project]
name = "esp32-presence-case"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "build123d>=0.9.1",
    "cadquery>=2.5.2",
]

[tool.uv.sources]
build123d = { git = "https://github.com/gumyr/build123d.git" }
